apiVersion: gitops.example.io/v1alpha1
kind: ClusterConfig
metadata:
  name: bankapp-eks
spec:
  clusterName: bankapp-eks
  apiServer: https://80D05A3EC6DE7F42CDD549C185C8023C.gr7.ap-southeast-1.eks.amazonaws.com
  oidcIssuerUrl: https://oidc.eks.ap-southeast-1.amazonaws.com/id/80D05A3EC6DE7F42CDD549C185C8023C
  region: ap-southeast-1
