apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: example-app
          image: nginx:1.27
          ports:
            - containerPort: 80

