apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/thuyein97/amazon-prime/k8s/overlays/prod?ref=main
images:
  - name: thuyein97/bankapp
    newName: docker.io/thuyein97/bankapp
    newTag: latest
