apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/thuyein97/amazon-prime/k8s/overlays/staging?ref=main
images:
- name: docker.io/thuyein97/bankapp
  newTag: 6e60bae
